// Generated from config/platforms.csv by `npm run platforms:generate -w server`. Do not edit by hand.

/** Every platform code, in the Platform filter's order, with its full name. */
export const PLATFORM_TABLE: readonly { code: string; name: string }[] = [
  { code: "WIN", name: "Windows" },
  { code: "MAC", name: "Macintosh" },
  { code: "NSW", name: "Nintendo Switch" },
  { code: "LIN", name: "Linux" },
  { code: "IOS", name: "iOS" },
  { code: "AND", name: "Android" },
  { code: "PS4", name: "PlayStation 4" },
  { code: "XONE", name: "Xbox One" },
  { code: "WEB", name: "Web Browser" },
  { code: "PS5", name: "PlayStation 5" },
  { code: "XSX", name: "Xbox Series X|S" },
  { code: "PS3", name: "PlayStation 3" },
  { code: "COIN", name: "Arcade" },
  { code: "PS2", name: "PlayStation 2" },
  { code: "DOS", name: "DOS" },
  { code: "X360", name: "Xbox 360" },
  { code: "PS1", name: "PlayStation" },
  { code: "VR", name: "VR" },
  { code: "C64", name: "Commodore C64/128" },
  { code: "DS", name: "Nintendo DS" },
  { code: "PSP", name: "PlayStation Portable" },
  { code: "WII", name: "Wii" },
  { code: "AMI", name: "Amiga" },
  { code: "HAND", name: "Dedicated handheld" },
  { code: "ZX", name: "ZX Spectrum" },
  { code: "VITA", name: "PlayStation Vita" },
  { code: "GBA", name: "Game Boy Advance" },
  { code: "3DS", name: "Nintendo 3DS" },
  { code: "SNES", name: "Super Nintendo Entertainment System" },
  { code: "CPC", name: "Amstrad CPC" },
  { code: "WIIU", name: "Wii U" },
  { code: "CELL", name: "Pre-smartphone mobile" },
  { code: "NES", name: "Nintendo Entertainment System" },
  { code: "GEN", name: "Sega Genesis/Mega Drive" },
  { code: "ST", name: "Atari ST" },
  { code: "NSW2", name: "Nintendo Switch 2" },
  { code: "GB", name: "Game Boy" },
  { code: "GBC", name: "Game Boy Color" },
  { code: "N64", name: "Nintendo 64" },
  { code: "AP2", name: "Apple II" },
  { code: "XBOX", name: "Xbox" },
  { code: "MSX", name: "MSX" },
  { code: "SAT", name: "Sega Saturn" },
  { code: "A8", name: "Atari 8-bit" },
  { code: "PDT", name: "Playdate" },
  { code: "GCN", name: "Nintendo GameCube" },
  { code: "PC-98", name: "PC-98" },
  { code: "2600", name: "Atari 2600" },
  { code: "STD", name: "Dedicated hardware" },
  { code: "DC", name: "Dreamcast" },
  { code: "WINP", name: "Windows Phone" },
  { code: "SMS", name: "Sega Master System" },
  { code: "PC-88", name: "PC-88" },
  { code: "BBCM", name: "BBC Micro" },
  { code: "STADIA", name: "Google Stadia" },
  { code: "GG", name: "Sega Game Gear" },
  { code: "PCE", name: "TurboGrafx-16/PC Engine" },
  { code: "X68K", name: "Sharp X68000" },
  { code: "3DO", name: "3DO" },
  { code: "FM-T", name: "FM Towns" },
  { code: "FM7", name: "FM-7" },
  { code: "MSX2", name: "MSX2" },
  { code: "SCD", name: "Sega CD" },
  { code: "VIC", name: "Commodore VIC-20" },
  { code: "X1", name: "Sharp X1" },
  { code: "TRS", name: "TRS-80" },
  { code: "COL", name: "ColecoVision" },
  { code: "C16", name: "Commodore C16/Plus 4" },
  { code: "INTV", name: "Intellivision" },
  { code: "OUYA", name: "Ouya" },
  { code: "ELK", name: "Acorn Electron" },
  { code: "CDI", name: "Philips CD-i" },
  { code: "AES", name: "Neo Geo AES" },
  { code: "ZX81", name: "Sinclair ZX81" },
  { code: "GS", name: "Apple IIGS" },
  { code: "TI99", name: "Texas Instruments TI-99" },
  { code: "DVD", name: "DVD Player" },
  { code: "HS", name: "Mattel HyperScan" },
  { code: "COCO", name: "TRS-80 Color Computer" },
  { code: "5200", name: "Atari 5200" },
  { code: "SG1K", name: "SG-1000" },
  { code: "LNX", name: "Atari Lynx" },
  { code: "WS", name: "WonderSwan" },
  { code: "ABOY", name: "Arduboy" },
  { code: "BBOS", name: "BlackBerry OS" },
  { code: "MVS", name: "Neo Geo MVS" },
  { code: "ODY2", name: "Odyssey 2 / Videopac G7000" },
  { code: "FIRETV", name: "Amazon Fire TV" },
  { code: "NGCD", name: "Neo Geo CD" },
  { code: "ECADE", name: "Evercade" },
  { code: "WSC", name: "WonderSwan Color" },
  { code: "JAG", name: "Atari Jaguar" },
  { code: "DRG", name: "Dragon 32/64" },
  { code: "NGCP", name: "Neo Geo Pocket Color" },
  { code: "WINM", name: "Windows Mobile" },
  { code: "7800", name: "Atari 7800" },
  { code: "VEC", name: "Vectrex" },
  { code: "PC-6X", name: "PC-60" },
  { code: "LEAP", name: "Leapster" },
  { code: "ACORN", name: "Acorn Archimedes" },
  { code: "UZE", name: "Uzebox" },
  { code: "SV", name: "Supervision" },
  { code: "LEXP", name: "Leapster Explorer/LeadPad Explorer" },
  { code: "NGAGE", name: "N-Gage" },
  { code: "VB", name: "Virtual Boy" },
  { code: "VOS", name: "visionOS" },
  { code: "G&W", name: "Game & Watch" },
  { code: "BEENA", name: "Advanced Pico Beena" },
  { code: "PICO", name: "Sega Pico" },
  { code: "PCFX", name: "PC-FX" },
  { code: "PIP", name: "Apple Pippin" },
  { code: "LCP", name: "Legacy computer platform (unspecified)" },
  { code: "32X", name: "Sega 32X" },
  { code: "PCW", name: "Amstrad PCW" },
  { code: "PET", name: "Commodore PET/CBM" },
  { code: "MZ", name: "Sharp MZ" },
  { code: "A2001", name: "Arcadia 2001" },
  { code: "ZEEBO", name: "Zeebo" },
  { code: "VC4K", name: "Interton VC 4000" },
  { code: "MDCB", name: "Mega Duck/Cougar Boy" },
  { code: "VSMILE", name: "V.Smile" },
  { code: "CHF", name: "Fairchild Channel F" },
  { code: "ASTR", name: "Bally Astrocade" },
  { code: "POKE", name: "Pok?mon Mini" },
  { code: "GMT", name: "Gamate" },
  { code: "ODY", name: "Odyssey" },
  { code: "ELEKTOR", name: "Elektor TV Games Computer" },
  { code: "PLAYDIA", name: "Playdia" },
  { code: "SCV", name: "Epoch Super Cassette Vision" },
  { code: "PALM", name: "Palm OS" },
  { code: "GCOM", name: "Game.com" },
  { code: "PYUTA", name: "Tomy Tutor / Py?ta" },
  { code: "RZ", name: "R-Zone" },
  { code: "BIK", name: "Terebikko" },
  { code: "OOPARTS", name: "OOParts" },
  { code: "GIZM", name: "Gizmondo" },
  { code: "LA", name: "LaserActive" },
  { code: "AMICO", name: "Intellivision Amico" },
  { code: "SAC", name: "Super A'Can" },
  { code: "DGBL", name: "Digiblast" },
  { code: "CDTV", name: "Commodore CDTV" },
  { code: "NGP", name: "Neo Geo Pocket" },
  { code: "APVS", name: "1292 Advanced Programmable Video System" },
  { code: "THOM", name: "Thomson MO/TO" },
  { code: "ZOD", name: "Tapwave Zodiac" },
  { code: "POLY", name: "Polymega" },
  { code: "ONLIVE", name: "OnLive Game System" },
  { code: "LEAPTV", name: "LeapTV" },
  { code: "TATUNG", name: "Tatung Einstein" },
  { code: "BLU", name: "Blu-ray Player" },
  { code: "PDP10", name: "PDP-10" },
  { code: "PLATO", name: "PLATO" },
  { code: "MBMV", name: "Microvision" },
  { code: "PC-50", name: "PC-50" },
  { code: "CASV", name: "Epoch Cassette Vision" },
  { code: "LOOPY", name: "Casio Loopy" },
  { code: "PCE2", name: "PC Engine SuperGrafx" },
  { code: "PDP11", name: "PDP-11" },
  { code: "M2", name: "Panasonic M2" },
  { code: "CD32X", name: "Sega CD 32X" },
  { code: "CAC", name: "Call-A-Computer" },
  { code: "NUON", name: "Nuon" },
  { code: "SNESCD", name: "Super NES CD-ROM" },
  { code: "AIRC", name: "AirConsole" },
  { code: "HP2100", name: "HP 2100" },
  { code: "MC", name: "Microcomputer" },
  { code: "HNG64", name: "Hyper Neo Geo 64" },
  { code: "QL", name: "Sinclair QL" },
  { code: "TELSTAR", name: "Coleco Telstar" },
  { code: "EXIDY", name: "Exidy Sorcerer" },
  { code: "GX4000", name: "Amstrad GX4000" },
  { code: "SOL20", name: "Sol-20" },
  { code: "JUNGLE", name: "Panasonic Jungle" },
  { code: "PDP8", name: "PDP-8" },
  { code: "ANAL", name: "Analogue electronics platforms" },
  { code: "EDSAC", name: "EDSAC" },
  { code: "PDP7", name: "PDP-7" },
  { code: "CDCC", name: "CDC Cyber" },
  { code: "PDS1", name: "Imlac PDS-1" },
  { code: "VC", name: "Virtual Console" },
  { code: "PDP1", name: "PDP-1" },
  { code: "GT40", name: "DEC GT40" },
  { code: "NIMROD", name: "Nimrod" },
  { code: "HP3000", name: "HP 3000" },
  { code: "SDSS", name: "SDS Sigma" },
  { code: "SCRST", name: "SwanCrystal" },
]

/** IGDB platform id → code. */
export const IGDB_PLATFORM_CODES: Readonly<Record<number, string>> = {
  3: "LIN",
  4: "N64",
  5: "WII",
  6: "WIN",
  7: "PS1",
  8: "PS2",
  9: "PS3",
  11: "XBOX",
  12: "X360",
  13: "DOS",
  14: "MAC",
  15: "C64",
  16: "AMI",
  18: "NES",
  19: "SNES",
  20: "DS",
  21: "GCN",
  22: "GBC",
  23: "DC",
  24: "GBA",
  25: "CPC",
  26: "ZX",
  27: "MSX",
  29: "GEN",
  30: "32X",
  32: "SAT",
  33: "GB",
  34: "AND",
  35: "GG",
  37: "3DS",
  38: "PSP",
  39: "IOS",
  41: "WIIU",
  42: "NGAGE",
  44: "ZOD",
  46: "VITA",
  47: "VC",
  48: "PS4",
  49: "XONE",
  50: "3DO",
  51: "NES",
  52: "COIN",
  53: "MSX2",
  55: "CELL",
  57: "WS",
  58: "SNES",
  59: "2600",
  60: "7800",
  61: "LNX",
  62: "JAG",
  63: "ST",
  64: "SMS",
  65: "A8",
  66: "5200",
  67: "INTV",
  68: "COL",
  69: "BBCM",
  70: "VEC",
  71: "VIC",
  72: "OUYA",
  73: "BBOS",
  74: "WINP",
  75: "AP2",
  77: "X1",
  78: "SCD",
  79: "MVS",
  80: "AES",
  82: "WEB",
  84: "SG1K",
  85: "ANAL",
  86: "PCE",
  87: "VB",
  88: "ODY",
  89: "MBMV",
  90: "PET",
  91: "ASTR",
  93: "C16",
  94: "C16",
  95: "PDP1",
  96: "PDP10",
  97: "PDP8",
  98: "GT40",
  99: "NES",
  100: "ANAL",
  101: "NIMROD",
  102: "EDSAC",
  103: "PDP7",
  104: "HP2100",
  105: "HP3000",
  106: "SDSS",
  107: "CAC",
  108: "PDP11",
  109: "CDCC",
  110: "PLATO",
  111: "PDS1",
  112: "MC",
  113: "ONLIVE",
  114: "AMI",
  115: "GS",
  116: "ACORN",
  117: "CDI",
  118: "FM-T",
  119: "NGP",
  120: "NGCP",
  121: "X68K",
  122: "NUON",
  123: "WSC",
  124: "SCRST",
  125: "PC-88",
  126: "TRS",
  127: "CHF",
  128: "PCE2",
  129: "TI99",
  130: "NSW",
  131: "SNESCD",
  132: "FIRETV",
  133: "ODY2",
  134: "ELK",
  135: "HNG64",
  136: "NGCD",
  137: "3DS",
  138: "VC4K",
  139: "APVS",
  140: "TELSTAR",
  141: "STD",
  142: "PC-50",
  143: "STD",
  144: "STD",
  145: "STD",
  146: "STD",
  147: "STD",
  148: "STD",
  149: "PC-98",
  150: "PCE",
  151: "COCO",
  152: "FM7",
  153: "DRG",
  154: "PCW",
  155: "TATUNG",
  156: "THOM",
  157: "PC-6X",
  158: "CDTV",
  159: "DS",
  161: "VR",
  162: "VR",
  163: "VR",
  164: "VR",
  165: "VR",
  166: "POKE",
  167: "PS5",
  169: "XSX",
  170: "STADIA",
  203: "STADIA",
  236: "EXIDY",
  237: "SOL20",
  238: "DVD",
  239: "BLU",
  240: "ZEEBO",
  274: "PCFX",
  306: "SNES",
  307: "G&W",
  308: "PLAYDIA",
  309: "ECADE",
  339: "PICO",
  372: "OOPARTS",
  373: "ZX81",
  374: "MZ",
  375: "CASV",
  376: "SCV",
  377: "STD",
  378: "GMT",
  379: "GCOM",
  380: "LOOPY",
  381: "PDT",
  382: "AMICO",
  384: "VR",
  385: "VR",
  386: "VR",
  387: "VR",
  388: "VR",
  389: "AIRC",
  390: "VR",
  405: "WINM",
  406: "QL",
  407: "HS",
  408: "MDCB",
  409: "LCP",
  410: "JAG",
  411: "HAND",
  412: "LEAP",
  413: "LEXP",
  414: "LEAPTV",
  415: "SV",
  416: "N64",
  417: "PALM",
  438: "ABOY",
  439: "VSMILE",
  440: "DC",
  441: "PS1",
  471: "VR",
  472: "VOS",
  473: "A2001",
  474: "GIZM",
  475: "RZ",
  476: "PIP",
  477: "JUNGLE",
  478: "M2",
  479: "BIK",
  480: "SAC",
  481: "PYUTA",
  482: "CD32X",
  486: "DGBL",
  487: "LA",
  504: "UZE",
  505: "ELEKTOR",
  506: "GX4000",
  507: "BEENA",
  508: "NSW2",
  509: "POLY",
  510: "GBA",
}
